language: node_js
addons:
  mariadb: '10.1'
node_js:
  - 'stable'
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test_jiskefet;'
install:
  - npm install
script:
  # - tslint -c tslint.json 'src/**/*.ts'
  - npm run lint
  - npm test
after_success: 
  - codecov
notifications:   
  slack: jiskefet:cGYsslE19X0IqoUwQXwAR9tT